[Mellanox] Add sensors.conf, pcie.yaml files, and update platform.json in SN5640 SimX
noaOrMlnx/sonic-buildimage pull request #41
Opened 2024-11-27 12:44 UTC by noaOrMlnx

#### Why I did it

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2024-12-01 15:10 UTC, dprital commented
@noaOrMlnx , Please update PR description

2024-12-01 15:11 UTC, dprital requested changes

2024-12-01 15:11 UTC, dprital commented on device/mellanox/x86_64-nvidia_sn5640_simx-r0/sensors.conf
> +# Copyright (c) 2019 - 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Please update the date to 2024

2024-12-02 11:42 UTC, noaOrMlnx commented on device/mellanox/x86_64-nvidia_sn5640_simx-r0/sensors.conf
> +# Copyright (c) 2019 - 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Done

2024-12-04 12:28 UTC, closed without merging